apps_to_guardian = {'Abbey College': 'Abbey College', 'Amity University [IN] London': 'Amity University [IN] London', 'Abingdon and Witney College': 'Abingdon and Witney College', 'University of Aberdeen': 'Aberdeen', 'Abertay University': 'Abertay University', 'Aberystwyth University': 'Aberystwyth', 'ABI College': 'ABI College', 'ALRA (The Academy of Live and Recorded Arts)': 'ALRA (The Academy of Live and Recorded Arts)', 'Access to Music': 'Access to Music', 'Accrington and Rossendale College': 'Accrington and Rossendale College', 'College of Agriculture, Food and Rural Enterprise': 'College of Agriculture, Food and Rural Enterprise', 'ACM (The Academy of Contemporary Music)': 'ACM (The Academy of Contemporary Music)', 'American InterContinental University - London': 'American InterContinental University - London', 'Buckinghamshire College Group': 'Buckinghamshire College Group', 'Amsterdam Fashion Academy': 'Amsterdam Fashion Academy', 'Anglia Ruskin University': 'Anglia Ruskin', 'AECC University College': 'AECC University College', 'Askham Bryan College': 'Askham Bryan College', 'Aston University, Birmingham': 'Aston', 'Bangor University': 'Bangor', 'Barnet and Southgate College': 'Barnet and Southgate College', 'Barnfield College, Luton': 'Barnfield College, Luton', 'Barking and Dagenham College': 'Barking and Dagenham College', 'Barony College': 'Barony College', 'Barnsley College Higher Education': 'Barnsley College Higher Education', 'Basingstoke College of Technology': 'Basingstoke College of Technology', 'University of Bath': 'Bath', 'Bicton College': 'Bicton College', 'Bath Spa University': 'Bath Spa', 'University of Bedfordshire': 'Bedfordshire', 'Bedford College Group': 'Bedford College Group', 'Birkbeck, University of London': 'Birkbeck', 'Birmingham City University': 'Birmingham City', 'Bell College': 'Bell College', 'University of Birmingham': 'Birmingham', 'Bexley College': 'Bexley College', 'Bishop Burton College': 'Bishop Burton College', 'Bishop Grosseteste University': 'Bishop Grosseteste University', 'BIMM Institute': 'BIMM Institute', 'Blackburn College': 'Blackburn College', 'Blackpool and the Fylde College': 'Blackpool and the Fylde College', 'Berkshire College of Agriculture': 'Berkshire College of Agriculture', 'University of Bolton': 'Bolton', 'Bournville College': 'Bournville College', 'Bournemouth University': 'Bournemouth', 'BPP University': 'BPP University', 'University of Bradford': 'Bradford', 'British Institute of Technology, England': 'British Institute of Technology, England', 'Bridgend College': 'Bridgend College', 'Burnley College': 'Burnley College', 'University Centre Somerset - Bridgwater & Taunton College': 'University Centre Somerset - Bridgwater & Taunton College', 'University of Brighton': 'Brighton', 'British Institute of Technology & E-commerce': 'British Institute of Technology & E-commerce', 'Brighton and Sussex Medical School': 'Brighton and Sussex Medical School', 'City College Brighton & Hove': 'City College Brighton & Hove', 'City of Bristol College': 'City of Bristol College', 'University of Bristol': 'Bristol', 'British College of Osteopathic Medicine': 'British College of Osteopathic Medicine', 'University of London Institute in Paris (University of London)': 'University of London Institute in Paris (University of London)', 'Brooklands College': 'Brooklands College', 'Brunel University London': 'Brunel', 'University College of Osteopathy': 'University College of Osteopathy', 'Brockenhurst College': 'Brockenhurst College', 'University of Buckingham': 'University of Buckingham', 'Brooksby Melton College': 'Brooksby Melton College', 'Bury College': 'Bury College', 'Buckinghamshire New University': 'Buckinghamshire New University', 'Burton College': 'Burton College', 'London South East Colleges (Bromley College)': 'London South East Colleges (Bromley College)', "Buckswood St George's": "Buckswood St George's", 'University Centre Calderdale College': 'University Centre Calderdale College', 'University of Cambridge': 'Cambridge', 'Canterbury Christ Church University': 'Canterbury Christ Church', 'EKC Group': 'EKC Group', 'Capel Manor College': 'Capel Manor College', 'Cardiff University': 'Cardiff', 'Cardiff Metropolitan University': 'Cardiff Met', 'Coleg Sir Gar': 'Coleg Sir Gar', 'Carshalton College': 'Carshalton College', 'CECOS London College of IT and Management': 'CECOS London College of IT and Management', 'University Campus Scarborough': 'University Campus Scarborough', 'University of Central Lancashire': 'Central Lancashire', 'Central Film School London': 'Central Film School London', 'Royal Central School of Speech and Drama, University of London': 'Royal Central School of Speech and Drama, University of London', 'City of Glasgow College': 'City of Glasgow College', 'University of Chester': 'Chester', 'University of Chichester': 'Chichester', 'City, University of London': 'City', 'City College, Birmingham': 'City College, Birmingham', 'The Manchester College (Formerly City College Manchester)': 'The Manchester College (Formerly City College Manchester)', 'City of Sunderland College': 'City of Sunderland College', 'City College Brighton and Hove': 'City College Brighton and Hove', 'The Northern School of Art (formerly Cleveland College of Art and Design)': 'The Northern School of Art (formerly Cleveland College of Art and Design)', 'Cliff College': 'Cliff College', 'University Centre Colchester at Colchester Institute': 'University Centre Colchester at Colchester Institute', 'Cornwall College': 'Cornwall College', 'Courtauld Institute of Art, University of London': 'Courtauld Institute of Art, University of London', 'City College Plymouth': 'City College Plymouth', 'Coventry University': 'Coventry', 'Conde Nast College of Fashion & Design': 'Conde Nast College of Fashion & Design', 'Craven College': 'Craven College', 'Creative Academy': 'Creative Academy', 'University Centre Croydon': 'University Centre Croydon', 'University for the Creative Arts': 'University for the Creative Arts', 'City of Wolverhampton College': 'City of Wolverhampton College', 'University of Cumbria': 'Cumbria', 'Dearne Valley College': 'Dearne Valley College', 'De Montfort University': 'De Montfort', 'University of Derby': 'Derby', 'North Devon College': 'North Devon College', 'Kirklees College (Formerly Dewsbury College)': 'Kirklees College (Formerly Dewsbury College)', 'Doncaster College and University Centre': 'Doncaster College and University Centre', 'Duchy College': 'Duchy College', 'Dudley College': 'Dudley College', 'University of Dundee': 'Dundee', 'Dunstable College': 'Dunstable College', 'Durham University': 'Durham', 'University of East Anglia UEA': 'UEA', 'East End Computing and Business College': 'East End Computing and Business College', 'East Lancashire Institute of Higher Education at Blackburn College': 'East Lancashire Institute of Higher Education at Blackburn College', 'Eastleigh College': 'Eastleigh College', 'University of East London': 'East London', 'East Riding College': 'East Riding College', 'Easton and Otley College': 'Easton and Otley College', 'Edge Hotel School': 'Edge Hotel School', 'Edge Hill University': 'Edge Hill', 'University of Edinburgh': 'Edinburgh', 'Edinburgh Napier University': 'Edinburgh Napier', 'University of Essex': 'Essex', 'University College of Estate Management': 'University College of Estate Management', 'European Business School, London': 'European Business School, London', 'European School of Economics': 'European School of Economics', 'ESCP Europe Business School': 'ESCP Europe Business School', 'European School of Osteopathy': 'European School of Osteopathy', 'University of Exeter': 'Exeter', 'Fairfield School of Business': 'Fairfield School of Business', 'Falmouth University': 'Falmouth', 'Fareham College': 'Fareham College', 'University Centre Farnborough': 'University Centre Farnborough', 'Fashion Retail Academy': 'Fashion Retail Academy', 'Furness College': 'Furness College', 'Futureworks': 'Futureworks', 'Gateshead College': 'Gateshead College', 'Gateway School of Recording': 'Gateway School of Recording', 'University of South Wales (formerly University of Glamorgan)': 'South Wales', 'Glamorgan Centre for Art and Design Technology': 'Glamorgan Centre for Art and Design Technology', 'University of Glasgow': 'Glasgow', 'Glasgow Caledonian University': 'Glasgow Caledonian', 'University of Gloucestershire': 'Gloucestershire', 'Glyndwr University, Wrexham': 'Glyndwr University, Wrexham', 'Goldsmiths, University of London': 'Goldsmiths', 'Great Yarmouth College': 'Great Yarmouth College', 'University of Greenwich': 'Greenwich', 'University Centre Grimsby': 'University Centre Grimsby', 'Guildford College': 'Guildford College', 'Hackney Community College': 'Hackney Community College', 'University Centre Hadlow': 'University Centre Hadlow', 'Halesowen College': 'Halesowen College', 'Halton College': 'Halton College', 'Harrogate College': 'Harrogate College', 'Harrow College': 'Harrow College', 'Harper Adams University': 'Harper Adams University', 'Havering College of Further and Higher Education': 'Havering College of Further and Higher Education', 'Hereford College of Arts': 'Hereford College of Arts', 'Hartpury University': 'Hartpury University', 'Harlow College': 'Harlow College', 'Heriot-Watt University': 'Heriot-Watt', 'University of Hertfordshire': 'Hertfordshire', 'Hertford Regional College': 'Hertford Regional College', 'Highbury College': 'Highbury College', 'Heythrop College (University of London)': 'Heythrop College (University of London)', 'University of the Highlands and Islands (UHI)': 'University of the Highlands and Islands (UHI)', 'Holborn College': 'Holborn College', 'Holy Cross Sixth Form College and University Centre': 'Holy Cross Sixth Form College and University Centre', 'Hopwood Hall College': 'Hopwood Hall College', 'University of Huddersfield': 'Huddersfield', 
'Hugh Baird College': 'Hugh Baird College', 'University of Hull': 'Hull', 'Hull York Medical School': 'Hull York Medical School', 'Hult International Business School': 'Hult International Business School', 'Institute of Contemporary Music Performance': 'Institute of Contemporary Music Performance', 'Istituto Marangoni London': 'Istituto Marangoni London', 'Imperial College London': 'Imperial College', 'The London Institute of Banking & Finance': 'The London Institute of Banking & Finance', 'Islamic College for Advanced Studies': 'Islamic College for Advanced Studies', 'John Ruskin College': 'John Ruskin College', 'Kaplan Holborn College': 'Kaplan Holborn College', 'Keele University': 'Keele', 'Kensington and Chelsea College': 'Kensington and Chelsea College', 'Kensington College of Business': 'Kensington College of Business', 'Kendal College': 'Kendal College', 'Kogan Academy of Dramatic Arts': 'Kogan Academy of Dramatic Arts', 'University of Kent': 'Kent', "King's College London, University of London": "King's College London", 'Kingston University': 'Kingston', 'Kirklees College': 'Kirklees College', 'KLC School of Design': 'KLC School of Design', 'Knowsley Community College': 'Knowsley Community College', 'Lewisham Southwark College': 'Lewisham Southwark College', 'The University of Wales, Lampeter': 'The University of Wales, Lampeter', 'Lancaster University': 'Lancaster', 'The University of Law': 'The University of Law', 'Lansdowne College': 'Lansdowne College', 'Leeds City College': 'Leeds City College', 'University of Leeds': 'Leeds', 'Leeds Trinity University': 'Leeds Trinity', 'Leeds Beckett University': 'Leeds Beckett', 'University of Leicester': 'Leicester', 'Leo Baeck College - Centre for Jewish Education': 'Leo Baeck College - Centre for Jewish Education', 'University of Lincoln': 'Lincoln', 'Lewisham College': 'Lewisham College', 'University of Liverpool': 'Liverpool', 'City of Liverpool College University Centre': 'City of Liverpool College University Centre', 'Liverpool Hope University': 'Liverpool Hope', 'Liverpool John Moores University': 'Liverpool John Moores', 'Grwp Llandrillo Menai': 'Grwp Llandrillo Menai', 'London Electronics College': 'London Electronics College', 'London Film Academy': 'London Film Academy', 'London College': 'London College', 'ARU London': 'ARU London', 'London School of Accountancy and Management': 'London School of Accountancy and Management', 'London Metropolitan University': 'London Met', 'London School of Business and Computing': 'London School of Business and Computing', 'London School of Commerce': 'London School of Commerce', 'London School of Science & Technology': 'London School of Science & Technology', 'London School of Economics and Political Science, University of London': 'London School of Economics', 'Bloomsbury Institute': 'Bloomsbury Institute', 'London South Bank University': 'London South Bank', 'London School of Marketing': 'London School of Marketing', 'Loughborough University': 'Loughborough', 'Lowestoft College': 'Lowestoft College', 'London College of Creative Media': 'London College of Creative Media', 'University of Luton': 'University of Luton', 'Macclesfield College': 'Macclesfield College', 'University of Manchester': 'Manchester', 'Manchester Metropolitan University': 'Manchester Met', 'Matthew Boulton College of Further and Higher Education': 'Matthew Boulton College of Further and Higher Education', 'Medipathways': 'Medipathways', 'Medway School of Pharmacy': 'Medway School of Pharmacy', 'Coleg Menai': 'Coleg Menai', 'Metanoia Institute': 'Metanoia Institute', 'Met Film School': 'Met Film School', 'Mid Cheshire College': 'Mid Cheshire College', 'Middlesbrough College': 'Middlesbrough College', 'Middlesex University': 'Middlesex', 'Mont Rose College of Management and Sciences': 'Mont Rose College of Management and Sciences', 'Milton Keynes College': 'Milton Keynes College', 'Moulton College': 'Moulton College', 'Mountview Academy of Theatre Arts': 'Mountview Academy of Theatre Arts', 'University Centre Myerscough': 'University Centre Myerscough', 'Nazarene Theological College': 'Nazarene Theological College', 'NCIUL': 'NCIUL', 'NPTC Group': 'NPTC Group', 'Newcastle University': 'Newcastle', 'Newham College London': 'Newham College London', 'New College Stamford': 'New College Stamford', 'New College, Swindon': 'New College, Swindon', 'Newman University, Birmingham': 'Newman', 'University of Northampton': 'Northampton', 'Norwich University of the Arts': 'Norwich University of the Arts', 'Greater Brighton Metropolitan College (formerly Northbrook College and City College)': 'Greater Brighton Metropolitan College (formerly Northbrook College and City College)', 'NESCOT': 'NESCOT', 'New College Telford': 'New College Telford', 'Norland College': 'Norland College', 'New College of the Humanities': 'New College of the Humanities', 'Glyndwr University (Formerly The North East Wales Institute of Higher Education)': 'Glyndwr University (Formerly The North East Wales Institute of Higher Education)', 'DN Colleges Group': 'DN Colleges Group', 'North Trafford College': 'North Trafford College', 'Northumbria University, Newcastle': 'Northumbria', 'Northumberland College': 'Northumberland College', 'North Warwickshire and South Leicestershire College': 'North Warwickshire and South Leicestershire College', 'Norton Radstock College': 'Norton Radstock College', 'University of Nottingham': 'Nottingham', 'Nottingham Trent University': 'Nottingham Trent', 'University Campus Oldham': 'University Campus Oldham', 'Oaklands College': 'Oaklands College', 'Activate Learning': 'Activate Learning', 'University of Oxford': 'Oxford', 'Oxford Brookes University': 'Oxford Brookes', 'University of Paisley': 'University of Paisley', 'University of London Institute in Paris': 'University of London Institute in Paris', 'Park Royal College': 'Park Royal College', 'Pearson College London (including Escape Studios)': 'Pearson College London (including Escape Studios)', 'Pembrokeshire College': 'Pembrokeshire College', 'Peninsula College of Medicine & Dentistry': 'Peninsula College of Medicine & Dentistry', 'Pershore Group of Colleges': 'Pershore Group of Colleges', 'Petroc': 'Petroc', "Peter Symonds' College": "Peter Symonds' College", 'Peterborough Regional College': 'Peterborough Regional College', 'University Centre Peterborough': 'University Centre Peterborough', 'Plumpton College': 'Plumpton College', 'University of Plymouth': 'Plymouth', 'Point Blank Music School': 'Point Blank Music School', 'University of Portsmouth': 'Portsmouth', 'Queen Margaret University, Edinburgh': 'Queen Margaret', 'Queen Mary University of London': 'Queen Mary', "Queen's University Belfast": "Queen's University Belfast", 'Ravensbourne University London': 'Ravensbourne University London', 'University of Reading': 'Reading', 'University Centre Reaseheath': 'University Centre Reaseheath', "Regent's University London": "Regent's University London", 'Richmond, The American International University in London': 'Richmond, The American International University in London', 'Richmond Upon Thames College': 'Richmond Upon Thames College', 'Arden University': 'Arden University', 'Riverside College Halton': 'Riverside College Halton', 'Robert Gordon University': 'Robert Gordon', 'University of Roehampton': 'Roehampton', 'Rose Bruford College': 'Rose Bruford College', 'RNN Group': 'RNN Group', 'Royal Agricultural University': 'Royal Agricultural University', 'Royal Academy of Dance': 'Royal Academy of Dance', 'Royal Holloway, University of London': 'Royal Holloway', 'Royal Veterinary College, University of London': 'Royal Veterinary College, University of London', 'Royal Welsh College of Music and Drama': 'Royal Welsh College of Music and Drama', 'Runshaw College': 'Runshaw College', 'Ruskin College': 'Ruskin College', "SRUC Scotland's Rural College": "SRUC Scotland's Rural College", 'University of Salford': 'Salford', 'SAE Institute': 'SAE Institute', 'Selby College': 'Selby College', 'Wiltshire College Salisbury (formerly Salisbury College)': 'Wiltshire College Salisbury (formerly Salisbury College)', 'Sandwell College of Further and Higher Education': 'Sandwell College of Further and Higher Education', 'SOAS University of London': 'SOAS', 'University Centre at Salford City College': 'University Centre at Salford City College', 'The School of Pharmacy (University of London)': 'The School of Pharmacy (University of London)', 'University of Sheffield': 'Sheffield', "St Patrick's College, London": "St Patrick's College, London", 'South and City College Birmingham': 'South and City College Birmingham', 'Sheffield Hallam University': 'Sheffield Hallam', 'Shrewsbury College': 'Shrewsbury College', 'Solihull College & University Centre': 'Solihull College & University Centre', 'University of Southampton': 'Southampton', 'Somerset College': 'Somerset College', 'Solent University (Southampton)': 'Solent', 'University Centre South Devon': 'University Centre South Devon', 'University Centre Sparsholt': 'University Centre Sparsholt', 'Southport College': 'Southport College', 'University of St Andrews': 'St Andrews', 'Southwark College': 'Southwark College', 'South Cheshire College': 'South Cheshire College', 'Havant and South Downs College': 'Havant and South Downs College', 'South Trafford College': 'South Trafford College', "St George's, University of London": "St George's, University of London", 'South Thames College': 'South Thames College', 'University Centre St Helens': 'University Centre St Helens', 'South Tyneside College': 'South Tyneside College', "Spurgeon's College": "Spurgeon's College", "St Mary's College Blackburn": "St Mary's College Blackburn", "St Mary's University, Twickenham": "St Mary's University, Twickenham", 'Southampton City College': 'Southampton City College', 'Stamford College': 'Stamford College', 'Stephenson College Coalville': 'Stephenson College Coalville', 
'Staffordshire University': 'Staffordshire', 'Stratford upon Avon College': 'Stratford upon Avon College', 'University of Stirling': 'Stirling', 'Trafford College Group': 'Trafford College Group', 'Stourbridge College': 'Stourbridge College', 'University of Strathclyde': 'Strathclyde', 'Stranmillis University College': 'Stranmillis University College', 'Strode College': 'Strode College', 'University of Suffolk': 'Suffolk', 'University of Sunderland': 'Sunderland', 'University of Surrey': 'Surrey', 'University of Sussex': 'Sussex', 'Sutton Coldfield College': 'Sutton Coldfield College', 'Swansea University': 'Swansea', 'Swindon College': 'Swindon College', 'Tameside College': 'Tameside College', 'BIMM London': 'BIMM London', 'Teesside University, Middlesbrough': 'Teesside', 'Tottenham Hotspur Foundation': 'Tottenham Hotspur Foundation', 'Tresham College': 'Tresham College', 'University of Wales Trinity Saint David': 'Trinity Saint David', 'Truro and Penwith College': 'Truro and Penwith College', 'Two Mile Ash ITT Partnership': 'Two Mile Ash ITT Partnership', 'Tyne Coast College': 'Tyne Coast College', 'UCFB': 'UCFB', 'UK College of Business and Computing': 'UK College of Business and Computing', 'Ulster University': 'Ulster', 'University of the West of Scotland': 'West of Scotland', 'University of the Arts London': 'University of the Arts London', 'UCL (University College London)': 'UCL', 'HCUC': 'HCUC', 'USP College': 'USP College', 'University of West London': 'West London', 'Wakefield College': 'Wakefield College', 'Walsall College': 'Walsall College', 'Waltham Forest College': 'Waltham Forest College', 'Warrington Collegiate': 'Warrington Collegiate', 'University of Warwick': 'Warwick', 'Welsh College of Horticulture': 'Welsh College of Horticulture', 'University Centre West Anglia': 'University Centre West Anglia', 'West Cheshire College': 'West Cheshire College', 'West Herts College': 'West Herts College', 'University Centre Weston': 'University Centre Weston', 'University of Westminster, London': 'Westminster', 'United Colleges Group': 'United Colleges Group', 'West Thames College': 'West Thames College', 'Weymouth College': 'Weymouth College', 'Wigan and Leigh College': 'Wigan and Leigh College', 'Wimbledon School of Art': 'Wimbledon School of Art', 'Wirral Metropolitan College': 'Wirral Metropolitan College', 'Wiltshire College and University Centre': 'Wiltshire College and University Centre', 'University of Wolverhampton': 'Wolverhampton', 'University of Winchester': 'Winchester', 'University of Worcester': 'Worcester', "Working Men's College": "Working Men's College", 'Writtle University College': 'Writtle University College', 'Yeovil College University Centre': 'Yeovil College University Centre', 'University of York': 'York', 'York St John University': 'York St John'}

hesa_to_guardian = {'AECC University College': 'AECC University College', 'Abertay University': 'Abertay University', 'Aberystwyth University': 'Aberystwyth', 'Anglia Ruskin University': 'Anglia Ruskin', 'Aston University': 'Aston', 'Bangor University': 'Bangor', 'Bath Spa University': 'Bath Spa', 'Birkbeck College': 'Birkbeck', 'Birmingham City University': 'Birmingham City', 'Bishop Grosseteste University': 'Bishop Grosseteste University', 'Bournemouth University': 'Bournemouth', 'Brunel University London': 'Brunel', 'Buckinghamshire New University': 'Buckinghamshire New University', 'Canterbury Christ Church University': 'Canterbury Christ Church', 'Cardiff Metropolitan University': 'Cardiff Met', 'Cardiff University': 'Cardiff', 'City, University of London': 'City', 'Courtauld Institute of Art': 'Courtauld Institute of Art', 'Coventry University': 'Coventry', 'Cranfield University': 'Cranfield University', 'De Montfort University': 'De Montfort', 'Edge Hill University': 'Edge Hill', 'Edinburgh Napier University': 'Edinburgh Napier', 'Falmouth University': 'Falmouth', 'Glasgow Caledonian University': 'Glasgow Caledonian', 'Global Banking School Limited': 'Global Banking School Limited', 'Glyndŵr University': 'Glyndŵr', 'Goldsmiths College': 'Goldsmiths', 'Guildhall School of Music and Drama': 'Guildhall School of Music and Drama', 'Harper Adams University': 'Harper Adams University', 'Hartpury University': 'Hartpury University', 'Heriot-Watt University': 'Heriot-Watt', 'Imperial College of Science, Technology and Medicine': 'Imperial College', 'Institute of Contemporary Music Performance': 'Institute of Contemporary Music Performance', 'Istituto Marangoni Limited': 'Istituto Marangoni Limited', 'Keele University': 'Keele', "King's College London": "King's College London", 'Kingston University': 'Kingston', 'Leeds Beckett University': 'Leeds Beckett', 'Leeds Trinity University': 'Leeds Trinity', 'Liverpool Hope University': 'Liverpool Hope', 'Liverpool John Moores University': 'Liverpool John Moores', 'London Business School': 'London Business School', 'London Metropolitan University': 'London Met', 'London School of Economics and Political Science': 'London School of Economics', 'London School of Hygiene and Tropical Medicine': 'London School of Hygiene and Tropical Medicine', 'London South Bank University': 'London South Bank', 'Loughborough University': 'Loughborough', 'Middlesex University': 'Middlesex', 'Newcastle University': 'Newcastle', 'Newman University': 'Newman', 'Norwich University of the Arts': 'Norwich University of the Arts', 'Oxford Brookes University': 'Oxford Brookes', 'Queen Margaret University, Edinburgh': 'Queen Margaret', 'Queen Mary University of London': 'Queen Mary', "Queen's University Belfast": "Queen's University Belfast", 'Ravensbourne University London': 'Ravensbourne University London', 'Regent College': 'Regent College', "Regent's University London": "Regent's University London", 'Robert Gordon University': 'Robert Gordon', 'Roehampton University': 'Roehampton', 'Rose Bruford College of Theatre and Performance': 'Rose Bruford College of Theatre and Performance', 'Royal Academy of Music': 'Royal Academy of Music', 'Royal Agricultural University': 'Royal Agricultural University', 'Royal College of Art': 'Royal College of Art', 'Royal College of Music': 'Royal College of Music', 'Royal Conservatoire of Scotland': 'Royal Conservatoire of Scotland', 'Royal Holloway and Bedford New College': 'Royal Holloway', 'Royal Northern College of Music': 'Royal Northern College of Music', 'SOAS University of London': 'SOAS', 'SRUC': 'SRUC', 'Sheffield Hallam University': 'Sheffield Hallam', 'Solent University': 'Solent', "St George's, University of London": "St George's, University of London", "St Mary's University College": "St Mary's University College", "St Mary's University, Twickenham": "St Mary's University, Twickenham", 'Staffordshire University': 'Staffordshire', 'Stranmillis University College': 'Stranmillis University College', 'Swansea University': 'Swansea', 'Teesside University': 'Teesside', 'The Manchester Metropolitan University': 'Manchester Met', 'The Nottingham Trent University': 'Nottingham Trent', 'The Open University': 'The Open University', 'The Royal Central School of Speech and Drama': 'The Royal Central School of Speech and Drama', 'The Royal Veterinary College': 'The Royal Veterinary College', 'The University of Aberdeen': 'Aberdeen', 'The University of Bath': 'Bath', 'The University of Birmingham': 'Birmingham', 'The University of Bolton': 'Bolton', 'The University of Bradford': 'Bradford', 'The University of Brighton': 'Brighton', 'The University of Bristol': 'Bristol', 'The University of Buckingham': 'The University of Buckingham', 'The University of Cambridge': 'Cambridge', 'The University of Central Lancashire': 'Central Lancashire', 'The University of Chichester': 'Chichester', 'The University of Dundee': 'Dundee', 'The University of East Anglia': 'The University of East Anglia', 'The University of East London': 'East London', 'The University of Edinburgh': 'Edinburgh', 'The University of Essex': 'Essex', 'The University of Exeter': 'Exeter', 'The University of Glasgow': 'Glasgow', 'The University of Greenwich': 'Greenwich', 'The University of Huddersfield': 'Huddersfield', 'The University of Hull': 'Hull', 'The University of Kent': 'Kent', 'The University of Lancaster': 'Lancaster', 'The University of Leeds': 'Leeds', 'The University of Leicester': 'Leicester', 'The University of Lincoln': 'Lincoln', 'The University of Liverpool': 'Liverpool', 'The University of Manchester': 'Manchester', 'The University of Northampton': 'Northampton', 'The University of Oxford': 'Oxford', 'The University of Portsmouth': 'Portsmouth', 'The University of Reading': 'Reading', 'The University of Salford': 'Salford', 'The University of Sheffield': 'Sheffield', 'The University of Southampton': 'Southampton', 'The University of St Andrews': 'St Andrews', 'The University of Stirling': 'Stirling', 'The University of Strathclyde': 'Strathclyde', 'The University of Sunderland': 'Sunderland', 'The University of Surrey': 'Surrey', 'The University of Sussex': 'Sussex', 'The University of Warwick': 'Warwick', 'The University of West London': 'West London', 'The University of Westminster': 'Westminster', 'The University of Winchester': 'Winchester', 'The University of Wolverhampton': 'Wolverhampton', 'The University of York': 'York', 'The University of the West of Scotland': 'West of Scotland', 'Trinity Laban Conservatoire of Music and Dance': 'Trinity Laban Conservatoire of Music and Dance', 'Ulster University': 'Ulster', 'University College London': 'University College London', 'University College of Estate Management': 'University College of Estate Management', 'University for the Creative Arts': 'University for the Creative Arts', 'University of Bedfordshire': 'Bedfordshire', 'University of Chester': 'Chester', 'University of Cumbria': 'Cumbria', 'University of Derby': 'Derby', 'University of Durham': 'Durham', 'University of Gloucestershire': 'Gloucestershire', 'University of Hertfordshire': 'Hertfordshire', 'University of Northumbria at Newcastle': 'Northumbria', 'University of Nottingham': 'Nottingham', 'University of Plymouth': 'Plymouth', 'University of South Wales': 'South Wales', 'University of St Mark and St John': 'University of St Mark and St John', 'University of Suffolk': 'Suffolk', 'University of Wales Trinity Saint David': 'Trinity Saint David', 'University of Worcester': 'Worcester', 'University of the Arts, London': 'University of the Arts, London', 'University of the Highlands and Islands': 'University of the Highlands and Islands', 'Writtle University College': 'Writtle University College', 'York St John University': 'York St John'}

# applications_to_hesa = 
 
guardian_to_hesa = {'ACM Guildford Limited': 'ACM Guildford Limited',
 'ACM London Limited': 'ACM London Limited',
 'Abertay University': 'Abertay University',
 'Aberystwyth University': 'Aberystwyth University',
 'Anglia Ruskin University Higher Education Corporation': 'Anglia Ruskin University',
 'Arden University Limited': 'Arden University',
 'Arts University Bournemouth, the': 'Arts University Bournemouth, the',
 'Askham Bryan College': 'Askham Bryan College',
 'Aston University': 'Aston University',
 'BIMM Limited': 'BIMM Limited',
 'Bangor University': 'Bangor University',
 'Barnsley College': 'Barnsley College',
 'Bath Spa University': 'Bath Spa University',
 'Belfast Metropolitan College': 'Belfast Metropolitan College',
 'Birkbeck College': 'Birkbeck College',
 'Birmingham City University': 'Birmingham City University',
 'Bishop Burton College': 'Bishop Burton College',
 'Bishop Grosseteste University': 'Bishop Grosseteste University',
 'Blackburn College': 'Blackburn College',
 'Blackpool and the Fylde College': 'Blackpool and the Fylde College',
 'Bloomsbury Institute Limited': 'Bloomsbury Institute',
 'Bournemouth University': 'Bournemouth University',
 'Bradford College': 'Bradford College',
 'Brighton and Sussex Medical School': 'Brighton and Sussex Medical School',
 'Brunel University London': 'Brunel University London',
 'Buckinghamshire New University': 'Buckinghamshire New University',
 'Canterbury Christ Church University': 'Canterbury Christ Church University',
 'Cardiff Metropolitan University': 'Cardiff Metropolitan University',
 'Cardiff University': 'Cardiff University',
 'City College Norwich': 'City College Norwich',
 'City College Plymouth': 'City College Plymouth',
 'City, University of London': 'City, University of London',
 'Colchester Institute': 'Colchester Institute',
 'Coleg Gwent': 'Coleg Gwent',
 'Cornwall College': 'Cornwall College',
 'Coventry University': 'Coventry University',
 'DN Colleges Group': 'DN Colleges Group',
 'David Game College Ltd': 'David Game College Ltd',
 'De Montfort University': 'De Montfort University',
 'Doreen Bird College of Performing Arts Ltd.': 'Doreen Bird College of Performing Arts Ltd.',
 'East Sussex College Group': 'East Sussex College Group',
 'Edge Hill University': 'Edge Hill University',
 'Edinburgh Napier University': 'Edinburgh Napier University',
 'Exeter College': 'Exeter College',
 'Falmouth University': 'Falmouth University',
 'Farnborough College of Technology': 'Farnborough College of Technology',
 'Fashion Retail Academy': 'Fashion Retail Academy',
 'Futureworks Training Limited': 'Futureworks',
 'Glasgow Caledonian University': 'Glasgow Caledonian University',
 'Glasgow School of Art': 'Glasgow School of Art',
 "Goldsmiths' College": "Goldsmiths' College",
 'Greater Brighton Metropolitan College': 'Greater Brighton Metropolitan College',
 'Grwp Llandrillo Menai': 'Grwp Llandrillo Menai',
 'Guildhall School of Music & Drama': 'Guildhall School of Music & Drama',
 'Harper Adams University': 'Harper Adams University',
 'Hartpury University': 'Hartpury University',
 'Heriot-Watt University': 'Heriot-Watt University',
 'Hugh Baird College': 'Hugh Baird College',
 'Hull College': 'Hull College',
 'Hull and York Medical School': 'Hull and York Medical School',
 'ICMP Management Limited': 'ICMP Management Limited',
 'ICON College of Technology and Management Ltd': 'ICON College of Technology and Management',
 'Imperial College of Science, Technology and Medicine': 'Imperial College of Science, Technology and Medicine',
 'Istituto Marangoni Limited': 'Istituto Marangoni Limited',
 'Kensington Education Foundation Limited': 'Kensington Education Foundation Limited',
 "King's College London": "King's College London",
 'Kingston University': 'Kingston University',
 'LTE Group': 'LTE Group',
 'Leeds Arts University': 'Leeds Arts University',
 'Leeds Beckett University': 'Leeds Beckett University',
 'Leeds City College': 'Leeds City College',
 'Leeds Conservatoire': 'Leeds Conservatoire',
 'Leeds Trinity University': 'Leeds Trinity University',
 'Liverpool Hope University': 'Liverpool Hope University',
 'Liverpool John Moores University': 'Liverpool John Moores University',
 'London Churchill College Ltd': 'London Churchill College Ltd',
 'London Metropolitan University': 'London Metropolitan University',
 'London South Bank University': 'London South Bank University',
 'London South East Colleges': 'London South East Colleges',
 'London Studio Centre Limited': 'London Studio Centre',
 'Loughborough College': 'Loughborough College',
 'Loughborough University': 'Loughborough University',
 'Manchester Metropolitan University': 'The Manchester Metropolitan University',
 'Medway School of Pharmacy': 'Medway School of Pharmacy',
 'Middlesex University': 'Middlesex University',
 'Mont Rose College of Management and Sciences Limited': 'Mont Rose College of Management and Sciences',
 'Myerscough College': 'Myerscough College',
 'NCG': 'NCG',
 'Nelson College London Limited': 'Nelson College London Limited',
 'New College Durham': 'New College Durham',
 'New College Swindon': 'New College Swindon',
 'Newman University': 'Newman University',
 'North West Regional College': 'North West Regional College',
 'Northern Regional College': 'Northern Regional College',
 'Norwich University of the Arts': 'Norwich University of the Arts',
 'Nottingham College': 'Nottingham College',
 'Nottingham Trent University': 'The Nottingham Trent University',
 'Nova Centric Limited': 'Nova Centric Limited',
 'Oxford Brookes University': 'Oxford Brookes University',
 'Pearson College Limited': 'Pearson College',
 'Petroc': 'Petroc',
 'Plymouth College of Art': 'Plymouth College of Art',
 'QAHE (UR) Limited': 'QAHE (UR) Limited',
 'Queen Margaret University, Edinburgh': 'Queen Margaret University, Edinburgh',
 'Queen Mary University of London': 'Queen Mary University of London',
 "Queen's University Belfast": "Queen's University Belfast",
 'RTC Education Ltd': 'RTC Education Ltd',
 'Ravensbourne University London': 'Ravensbourne University London',
 'Reaseheath College': 'Reaseheath College',
 "Regent's University London Limited": "Regent's University London",
 'Robert Gordon University': 'Robert Gordon University',
 'Roehampton University': 'Roehampton University',
 'Rose Bruford College of Theatre and Performance': 'Rose Bruford College of Theatre and Performance',
 'Royal Conservatoire of Scotland': 'Royal Conservatoire of Scotland',
 'Royal Holloway and Bedford New College': 'Royal Holloway and Bedford New College',
 'SAE Education Limited': 'SAE Education Limited',
 'SRUC': 'SRUC',
 'Sheffield College, The': 'Sheffield College, The',
 'Sheffield Hallam University': 'Sheffield Hallam University',
 'Solent University, Southampton': 'Solent University',
 'Solihull College and University Centre': 'Solihull College and University Centre',
 'South & City College Birmingham': 'South & City College Birmingham',
 'South Devon College': 'South Devon College',
 'South Essex College of Further and Higher Education': 'South Essex College of Further and Higher Education',
 'South Thames Colleges Group': 'South Thames Colleges Group',
 'South West College': 'South West College',
 'Southern Regional College': 'Southern Regional College',
 'Sparsholt College': 'Sparsholt College',
 "St Mary's University College": "St Mary's University College",
 "St Mary's University, Twickenham": "St Mary's University, Twickenham",
 "St. George's Hospital Medical School": "St. George's Hospital Medical School",
 'Staffordshire University': 'Staffordshire University',
 'Stranmillis University College': 'Stranmillis University College',
 'Swansea University': 'Swansea University',
 'TEC Partnership': 'TEC Partnership',
 'Teesside University': 'Teesside University',
 'The Conservatoire for Dance and Drama': 'Conservatoire for Dance and Drama',
 'The Liverpool Institute for Performing Arts': 'The Liverpool Institute for Performing Arts',
 'The London School of Economics and Political Science': 'London School of Economics and Political Science',
 'The Northern School of Art': 'The Northern School of Art',
 'The Oldham College': 'The Oldham College',
 'The Royal Agricultural University': 'Royal Agricultural University',
 'The Royal Veterinary College': 'The Royal Veterinary College',
 'The School of Oriental and African Studies': 'The School of Oriental and African Studies',
 'The University of Bath': 'The University of Bath',
 'The University of Birmingham': 'The University of Birmingham',
 'The University of Bolton': 'The University of Bolton',
 'The University of Bradford': 'The University of Bradford',
 'The University of Buckingham': 'The University of Buckingham',
 'The University of Chichester': 'The University of Chichester',
 'The University of Cumbria': 'University of Cumbria',
 'The University of East Anglia': 'The University of East Anglia',
 'The University of Essex': 'The University of Essex',
 'The University of Huddersfield': 'The University of Huddersfield',
 'The University of Hull': 'The University of Hull',
 'The University of Kent': 'The University of Kent',
 'The University of Lancaster': 'The University of Lancaster',
 'The University of Law Limited': 'The University of Law',
 'The University of Leeds': 'The University of Leeds',
 'The University of Leicester': 'The University of Leicester',
 'The University of Liverpool': 'The University of Liverpool',
 'The University of Manchester': 'The University of Manchester',
 'The University of Northampton': 'The University of Northampton',
 'The University of Reading': 'The University of Reading',
 'The University of Salford': 'The University of Salford',
 'The University of Sheffield': 'The University of Sheffield',
 'The University of Surrey': 'The University of Surrey',
 'The University of Warwick': 'The University of Warwick',
 'The University of West London': 'The University of West London',
 'The University of Westminster': 'The University of Westminster',
 'Trinity Laban Conservatoire of Music and Dance': 'Trinity Laban Conservatoire of Music and Dance',
 'Truro and Penwith College': 'Truro and Penwith College',
 'UCFB College of Football Business Limited': 'UCFB College of Football Business Limited',
 'UCK Limited': 'UCK Limited',
 'UK College of Business and Computing Ltd': 'UK College of Business and Computing',
 'University College Birmingham': 'University College Birmingham',
 'University College London': 'University College London',
 'University for the Creative Arts': 'University for the Creative Arts',
 'University of Aberdeen': 'The University of Aberdeen',
 'University of Bedfordshire': 'University of Bedfordshire',
 'University of Brighton': 'The University of Brighton',
 'University of Bristol': 'The University of Bristol',
 'University of Cambridge': 'The University of Cambridge',
 'University of Central Lancashire': 'The University of Central Lancashire',
 'University of Chester': 'University of Chester',
 'University of Derby': 'University of Derby',
 'University of Dundee': 'The University of Dundee',
 'University of Durham': 'University of Durham',
 'University of East London': 'The University of East London',
 'University of Edinburgh': 'The University of Edinburgh',
 'University of Exeter': 'The University of Exeter',
 'University of Glasgow': 'The University of Glasgow',
 'University of Gloucestershire': 'University of Gloucestershire',
 'University of Greenwich': 'The University of Greenwich',
 'University of Hertfordshire': 'University of Hertfordshire',
 'University of Keele': 'University of Keele',
 'University of Lincoln': 'The University of Lincoln',
 'University of Newcastle': 'University of Newcastle',
 'University of Northumbria at Newcastle': 'University of Northumbria at Newcastle',
 'University of Nottingham, The': 'University of Nottingham',
 'University of Plymouth': 'University of Plymouth',
 'University of Portsmouth': 'The University of Portsmouth',
 'University of South Wales': 'University of South Wales',
 'University of Southampton': 'The University of Southampton',
 'University of St Andrews': 'The University of St Andrews',
 'University of St Mark & St John': 'University of St Mark & St John',
 'University of Stirling': 'The University of Stirling',
 'University of Strathclyde': 'The University of Strathclyde',
 'University of Suffolk': 'University of Suffolk',
 'University of Sunderland': 'The University of Sunderland',
 'University of Sussex': 'The University of Sussex',
 'University of Ulster': 'University of Ulster',
 'University of Wales Trinity Saint David': 'University of Wales Trinity Saint David',
 'University of Winchester': 'The University of Winchester',
 'University of Wolverhampton': 'The University of Wolverhampton',
 'University of Worcester': 'University of Worcester',
 'University of York': 'The University of York',
 'University of the Arts, London': 'University of the Arts, London',
 'University of the Highlands and Islands': 'University of the Highlands and Islands',
 'University of the West of England, Bristol': 'University of the West of England, Bristol',
 'University of the West of Scotland': 'The University of the West of Scotland',
 'Warwickshire College': 'Warwickshire College',
 'West Suffolk College': 'West Suffolk College',
 'Weston College of Further and Higher Education': 'Weston College of Further and Higher Education',
 'Wigan and Leigh College': 'Wigan and Leigh College',
 'Wrexham Glyndwr University': 'Wrexham Glyndwr University',
 'Writtle University College': 'Writtle University College',
 'York St John University': 'York St John University'}